[versions]
accompanist-systemuicontroller = "0.34.0"
acra-dialog = "5.11.3"
agp = "8.3.1"
android-database-sqlcipher = "4.5.4"
animatedNavigationBar = "1.0.0"
appyx-navigation-android = "2.0.0-alpha10"
arrow = "1.2.4"
coil-compose = "2.6.0"
constraintlayout-compose = "1.0.1"
core-splashscreen = "1.0.1"
dagger-android = "2.51.1"
datastore = "1.0.0"
detekt = "1.23.6"
desugar_jdk_libs = "2.0.4"
dependencygraph = "0.12"
dependencycheck = "9.0.10"
exoplayer-ui = "2.19.1"
haze-materials = "0.6.2"
hilt-android = "2.51.1"
jUnit5Version = "5.10.2"
assertionsVersion = "5.8.1"
mockkVersion = "1.13.10"
lottieVersion = "6.4.0"
hilt-compiler = "1.2.0"
hilt-work = "1.2.0"
hilt-navigation-compose = "1.2.0"
jakarta-inject-api = "2.0.1"
jsoup = "1.17.2"
konsist = "0.15.1"
kopykat-ksp = "1.0.4"
kotest-runner-junit5 = "5.8.1"
kotlin = "1.9.23"
ktlint = "12.1.0"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
kotlinx-collections-immutable = "0.3.7"
kotlinx-coroutines-android = "1.8.0"
kotlinx-datetime = "0.5.0"
kotlinx-serialization-json = "1.6.3"
ktor-client-content-negotiation = "2.3.9"
ktor-client-okhttp = "2.3.9"
quiver = "0.5.1"
lifecycle-runtime-ktx = "2.7.0"
activity-compose = "1.8.2"
compose-bom = "2024.04.00"
ktorfit = "1.12.0"
hilt = "2.51"
ksp = "1.9.23-1.0.19"
logging-interceptor = "5.0.0-alpha.12"
molecule-runtime = "1.4.2"
orbit-core = "7.0.1"
paging-runtime-ktx = "3.3.0-beta01"
radiobrowser4j = "3.0.0"
robolectric = "4.12.1"
roborazzi = "1.11.0"
room-runtime = "2.6.1"
runtime-tracing = "1.0.0-beta01"
secrets-gradle-plugin = "2.0.1"
serialization = "1.9.23"
sqlite = "2.4.0"
timber = "5.0.1"
tink-android = "1.13.0"
truth = "1.4.2"
turbine = "1.1.0"
work-multiprocess = "2.9.0"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.2.3"

[libraries]
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist-systemuicontroller" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }

acra-advanced-scheduler = { module = "ch.acra:acra-advanced-scheduler", version.ref = "acra-dialog" }
acra-dialog = { module = "ch.acra:acra-dialog", version.ref = "acra-dialog" }
acra-http = { module = "ch.acra:acra-http", version.ref = "acra-dialog" }
acra-limiter = { module = "ch.acra:acra-limiter", version.ref = "acra-dialog" }
acra-mail = { module = "ch.acra:acra-mail", version.ref = "acra-dialog" }


acra-notification = { module = "ch.acra:acra-notification", version.ref = "acra-dialog" }
acra-toast = { module = "ch.acra:acra-toast", version.ref = "acra-dialog" }
android-database-sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "android-database-sqlcipher" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }


androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }

androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }

androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-compiler" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }

androidx-paging-common-ktx = { module = "androidx.paging:paging-common-ktx", version.ref = "paging-runtime-ktx" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-runtime-ktx" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging-runtime-ktx" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room-runtime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }

androidx-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version.ref = "runtime-tracing" }

androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "work-multiprocess" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-multiprocess" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "work-multiprocess" }

animated-navigation-bar = { module = "com.exyte:animated-navigation-bar", version.ref = "animatedNavigationBar" }
appyx-navigation-android = { module = "com.bumble.appyx:appyx-navigation-android", version.ref = "appyx-navigation-android" }
appyx-processor = { module = "com.bumble.appyx:appyx-processor", version.ref = "appyx-navigation-android" }
backstack-android = { module = "com.bumble.appyx:backstack-android", version.ref = "appyx-navigation-android" }

radiobrowser4j = { module = "de.sfuhrm:radiobrowser4j", version.ref = "radiobrowser4j" }
spotlight-android = { module = "com.bumble.appyx:spotlight-android", version.ref = "appyx-navigation-android" }

dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger-android" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger-android" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger-android" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger-android" }

jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject-api" }

ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-client-content-negotiation" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor-client-content-negotiation" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
roborazzi = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { module = "io.github.takahirom.roborazzi:roborazzi-compose", version.ref = "roborazzi" }

secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secrets-gradle-plugin" }

arrow-stack = { group = "io.arrow-kt", name = "arrow-stack", version.ref = "arrow" }
arrow-core = { module = "io.arrow-kt:arrow-core", name = "arrow-core" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", name = "arrow-fx-coroutines" }
arrow-annotations = { module = "io.arrow-kt:arrow-annotations", name = "arrow-annotations" }
arrow-atomic = { module = "io.arrow-kt:arrow-atomic", name = "arrow-atomic" }
arrow-fx-stm = { module = "io.arrow-kt:arrow-fx-stm", name = "arrow-fx-stm" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", name = "arrow-optics" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience", name = "arrow-resilience" }

arrow-core-retrofit = { module = "io.arrow-kt:arrow-core-retrofit", version.ref = "arrow" }
arrow-core-serialization = { module = "io.arrow-kt:arrow-core-serialization", version.ref = "arrow" }
arrow-optics-ksp-plugin = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }
arrow-optics-reflect = { module = "io.arrow-kt:arrow-optics-reflect", version.ref = "arrow" }

kopykat-ksp = { module = "at.kopyk:kopykat-ksp", version.ref = "kopykat-ksp" }

coil = { module = "io.coil-kt:coil", version.ref = "coil-compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil-compose" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil-compose" }
coil-test = { module = "io.coil-kt:coil-test", version.ref = "coil-compose" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil-compose" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }

exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer-ui" }
exoplayer-dash = { module = "com.google.android.exoplayer:exoplayer-dash", version.ref = "exoplayer-ui" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer-ui" }

haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze-materials" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze-materials" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest-runner-junit5" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest-runner-junit5" }

kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-android" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-client-okhttp" }

ktorfit-ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit" }
ktorfit-lib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }

quiver-test = { module = "app.cash.quiver:lib-test", version.ref = "quiver" }
quiver = { module = "app.cash.quiver:lib", version.ref = "quiver" }

lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieVersion" }


lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
molecule-runtime = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule-runtime" }

orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit-core" }
orbit-core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbit-core" }
orbit-test = { module = "org.orbit-mvi:orbit-test", version.ref = "orbit-core" }
orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit-core" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

tink-android = { module = "com.google.crypto.tink:tink-android", version.ref = "tink-android" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }


junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jUnit5Version" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jUnit5Version" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jUnit5Version" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "assertionsVersion" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

material3 = { group = "androidx.compose.material3", name = "material3" }

ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.6.5" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

utils-testing-ui-activity = { module = "com.bumble.appyx:utils-testing-ui-activity", version.ref = "appyx-navigation-android" }
utils-testing-ui = { module = "com.bumble.appyx:utils-testing-ui", version.ref = "appyx-navigation-android" }

uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
android_library = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
dependencygraph = { id = "com.savvasdalkitsis.module-dependency-graph", version.ref = "dependencygraph" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
androidTest = { id = "com.android.test", version.ref = "agp" }